In [3]:
import numpy as np

In [4]:
seq1 = np.linspace(0,10,21)
seq1

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [5]:
seq2 = np.arange(0,10,2)
seq2

array([0, 2, 4, 6, 8])

In [7]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
A[1,2]

6

In [12]:
#检查多行和多列
A[0,:]

array([0, 1, 2, 3])

In [13]:
A[[0,1],:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
# 提取子矩阵

A[[1,3],[0,2]]
#此处是将（1，0）和（3，2）配对

array([ 4, 14])

In [16]:
A[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [17]:
A[[1,3]][:,[0,2]]

array([[ 4,  6],
       [12, 14]])

In [18]:
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [19]:
#提取子矩阵更方便的方式

idx = np.ix_([1,3],[0,2,3])
A[idx]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [20]:
# 切片同样可以达到一样的效果，这是因为切片可以直接取完整列
A[1:4:2,:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [21]:
A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

In [22]:
# boolean型
keep_rows = np.zeros(A.shape[0],bool)

In [23]:
keep_rows[[1,3]] = True

In [24]:
keep_rows

array([False,  True, False,  True])

In [26]:
np.all(keep_rows == np.array([0,1,0,1]))

True

In [28]:
# 这只是说明在数值上两者相同，但py对待两者是完全不用的看法
A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [ ]:
# 但在np.ix_()中两者又是一样的