In [2]:
print ('fit a model with',11,'variables')

fit a model with 11 variables


In [3]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [4]:
"hello"+" "+"world"

'hello world'

In [6]:
# 列表
x = [3,4,5]

In [7]:
y = [4,9,7]

In [8]:
x + y

[3, 4, 5, 4, 9, 7]

In [9]:
import numpy as np

In [10]:
x = np.array([3,4,5])

In [11]:
y = np.array([4,9,7])

In [12]:
x + y

array([ 7, 13, 12])

In [13]:
x = np.array([[1,2],[3,4]])

In [14]:
x.ndim

2

In [15]:
x.dtype

dtype('int32')

In [16]:
x.shape#查看形状

(2, 2)

In [21]:
x.reshape((1,4))
print(x)

[[1 2]
 [3 4]]


In [22]:
x.ndim

2

In [23]:
x.reshape((2,2))
print(x)

[[1 2]
 [3 4]]


In [24]:
x.reshape((4,1))
print(x)

[[1 2]
 [3 4]]


In [25]:
y = np.array([1,2,3,4,5,6,7,8])
print(y)

[1 2 3 4 5 6 7 8]


In [28]:
y_reshape = y.reshape((4,2)) #reshape后要赋值才行
print(y_reshape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
#修改y_reshape同样会修改了y
y_reshape[0,0]=5
print(y_reshape)
print(y)

[[5 2]
 [3 4]
 [5 6]
 [7 8]]
[5 2 3 4 5 6 7 8]


In [34]:
z = np.random.normal((1,2))

In [35]:
print(z)

[0.33142532 2.31928207]


In [37]:
# 计算相关矩阵（系数是相关系数）
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
np.corrcoef(x,y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
z = np.random.normal(size=50)#不指定size，此处其识别为loc

49.948747009025254


In [45]:
k = z + np.random.normal(loc=110,size=50)

In [46]:
np.corrcoef(z,k)

array([[1.        , 0.72731425],
       [0.72731425, 1.        ]])

In [48]:
#设计随机种子可让获得确切的结果
rng = np.random.default_rng(2023)
print(rng.normal(scale =5,size = 2))

[3.00860647 5.75809485]


In [49]:
k.sum()

5509.485380733198

In [50]:
k.var() #注意此处的var不是修正样本偏差

2.2466699841948325

In [54]:
#对于行和列同样可以求sum等
y_reshape.sum(axis = 0)

array([20, 20])

In [55]:
#如果要指定行求和，必须将行先提取出来
y_first_row = y_reshape[0,:]

In [56]:
y_first_row.sum()

7